name: Publish
on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  build:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write

    environment:
      # environment created automatically by GitHub
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v27
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Build
        run: cd docs && nix-shell --run "mdbook build"

      - name: Archive book
        uses: actions/upload-artifact@v4
        with:
          name: book
          path: docs/book/*

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: "docs/book"

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
